[build.env]
passthrough = ["RUSTC_WRAPPER"]

[target.i686-pc-windows-msvc]
image = "ghcr.io/cross-rs/i686-pc-windows-msvc-cross:local"
pre-build = ["apt-get update", "apt-get install -y protobuf-compiler"]
