cargo-features = ["per-package-target"]

[package]
name = "hooks"
version = "0.1.0"
edition = "2021"
# forced-target = "i686-pc-windows-gnu"
forced-target = "i686-pc-windows-msvc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[[bin]]
name = "hook-loader"

[dependencies]
anyhow = "1.0.75"
dll-syringe = "0.15.2"
hooks-proc = { path = "hooks-proc" }
region = "3.0.0"
retour = { version = "0.3.1", features = ["thiscall-abi", "static-detour"] }
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.50"
toml = "0.8"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
sha2 = "0.10.8"

[dependencies.windows]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_System",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
]
