cargo-features = ["per-package-target"]

[package]
name = "hooks"
version = "0.1.0"
edition = "2021"
# forced-target = "i686-pc-windows-gnu"
forced-target = "i686-pc-windows-msvc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[[bin]]
name = "hook-loader"

[dependencies]
anyhow = "1.0.75"
dll-syringe = "0.15.2"
hooks-proc = { path = "hooks-proc" }
region = "3.0.0"
retour = { version = "0.3.1", features = ["thiscall-abi", "static-detour"] }
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.50"
toml = "0.8"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
sha2 = "0.10.8"
tonic = "0.10.2"
server_api = { path = "../api", package = "api" }
tokio = { version = "1.34.0", features = ["rt-multi-thread"] }
imgui = "0.11.0"
crossbeam-channel = "0.5.8"
url = { version = "2.5.0", features = ["serde"] }

[dependencies.hudhook]
version = "0.5.0"
default-features = false
features = ["dx9", "dx11"]

[dependencies.windows]
version = "0.51.1" # hudhook
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    # "Win32_Graphics_Direct3D",
    # "Win32_Graphics_Direct3D9",
    "Win32_System_Com",
    "Win32_System_Environment",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]
