[package]
name = "dedicated_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
default-run = "dedicated_server"

[dependencies]
argh = "0.1.12"
argon2 = "0.5.2"
byteorder = "1.4"
color-eyre = "0.6.2"
eyre = "0.6.8"
hmac = "0.12"
md-5 = "0.10"
num_enum = "0.7"
quazal = { path = "../quazal" }
quazal-macros = { path = "../quazal-macros" }
rand = "0.8.5"
serde = "1.0.193"
server_api = { path = "../api", package = "api" }
slog = { version = "2.7", features = ["max_level_trace"] }
sloggers = { version = "2.0", features = ["json"] }
sodiumoxide = "0.2"
sqlx = { version = "0.7.1", features = ["runtime-tokio", "sqlite"] }
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["rt-multi-thread"] }
toml = "0.8.8"
tonic = "0.10.2"
tonic-async-interceptor = "0.10.0"

[dev-dependencies]
diff = "0.1.13"
